---
title: "Dialing-in instructions for participants"
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

## read in data
path <- getwd()
past <- as.data.frame(read_excel(paste(path, "/data/past.xlsx", sep = ""), col_types = NULL))

# last issue 
last <- 2022

source(paste(path, "/functions/colFmt.r", sep = ""))

path <- "C:/rufibach/70_Service/EFSPI/workshop/20240911_9th_EFSPI_RegStat_Basel/30_registrations/"

path.data     <- paste(path, "data/", sep = "")
path.code     <- paste(path, "code/", sep = "")
path.depot    <- "C:/rufibach/05_Depot/"
path.map      <- paste(path.depot, "mapping/", sep = "")

source(paste(path.code, "prepTable.r", sep = ""), echo = FALSE)

## input and prepare registration data
source(paste(path.code, "input_prepare_data.r", sep = ""), echo = FALSE)
source(paste(path.code, "isValidEmail.r", sep = ""), echo = FALSE)

source(paste(path, "p0_initialize.r", sep = ""))
source(paste(path, "code/input_prepare_data.r", sep = ""), echo = FALSE)

dat <- with(filter(reg2, type %in% c("HTA", "Regulator")), table(inst2, mode))
```

# Introduction

You have registered for the `r paste("[EFSPI regulatory statistics workshop ", last + 1, "](", past[past[, "Year"] == last + 1, "Program"], ")", sep = "")`. This document provides necessary information for virtual participants to dial in to the zoom meetings at the day of the event. For any further questions please do not hesitate to reach out to one of the [local organizing committee members](local.html).

# Zoom instructions

- Every registered participant has received calendar invites for both days. These contain the dial-in details.
- `r colFmt("Day 1")`: Use this [zoom link](https://roche.zoom.us/j/92502410017) to dial in, with passcode 130923.
- `r colFmt("Day 2")`: Use this [zoom link](https://roche.zoom.us/j/94065878061) to dial in, with passcode 140923
- Attendees are invited to ask questions through zoom's Q&A functionality.
- Status of registrations: Find this [here](https://efspieurope.github.io/workshop/data/2023/analysis2023.html). We have `r nrow(reg2)` registrations from `r length(unique(reg2$country2))` countries as of now, with `r table(reg2$mode)[1]` face-to-face. `r sum(dat)` colleagues from regulatory agencies registered so far.

# Face-to-face attendance

- **Venue**: The event takes place in the Biozentrum in Basel ([directions](next.html)), in the Maurice Müller Lecture hall in the basement.
- **WLAN in the Biozentrum**: Connect to Unibas visitor. It will ask for your mobile phone number for confirmation.
- Upon arrival we ask you to register at the conference desk and to pick up your badge.

# Posting of slides and recordings

As soon as we get approval from speakers links to slidedecks and recordings will be posted [here](past.html). This may take a few days or even weeks, depending on the responsiveness of contributors. `r colFmt("Please do not send emails to us asking about postings. They will happen for those contributors who agree.")`

# Questions?

For feedback and questions send an email to [info@efspiworkshop.org](mailto:info@efspiworkshop.org).



