---
title: "Local organizing Committee"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

## read in data
path <- getwd()
source(paste(path, "/functions/inputData.r", sep = ""))
res <- inputData()

past <- as.data.frame(read_excel(paste(path, "/data/data.xlsx", sep = ""), col_types = NULL))
sci22 <- as.data.frame(read_excel(paste(path, "/data/2022/scicom2022.xlsx", sep = ""), col_types = NULL))
sci22 <- arrange(sci22, desc(Local), desc(SciCom), Gender, Last)

sci23 <- as.data.frame(read_excel(paste(path, "/data/2023/scicom2023.xlsx", sep = ""), col_types = NULL))
sci23 <- arrange(sci23, desc(Local), desc(SciCom), Gender, Last)

sci24 <- as.data.frame(read_excel(paste("C:/rufibach/70_Service/EFSPI/workshop/20240911_9th_EFSPI_RegStat_Basel/roster.xlsx", sep = ""), col_types = NULL))
sci24 <- arrange(sci24, desc(Local), desc(SciCom), Gender, Last)

sci25 <- as.data.frame(read_excel(paste("C:/rufibach/70_Service/EFSPI/workshop/20250910_10th_EFSPI_RegStat_Basel/roster.xlsx", sep = ""), col_types = NULL))
sci25 <- arrange(sci25, desc(Local), desc(SciCom), Gender, Last)

source(paste(path, "/functions/colFmt.r", sep = ""))
```

# 2025

The members of the local organizing committee in 2025 are:

```{r, include=TRUE, echo=FALSE}
sci25[, "email"] <- mailmerge(paste(sci25[, "First"], " ", sci25[, "Last"], sep = ""), sci25[, "email"])
kable(filter(sci25, Local == 1)[, c("First", "Last", "Type", "Affiliation", "email")], align = "ll")
```

# 2024

The members of the local organizing committee in 2024 were:

```{r, include=TRUE, echo=FALSE}
#sci24[, "email"] <- paste("[", sci24[, "First"], " ", sci24[, "Last"], "](mailto:", sci24[, "email"], ")", sep = "")
kable(filter(sci24, Local == 1)[, c("First", "Last", "Type", "Affiliation")], align = "ll")
```

# 2023

The members of the local organizing committee in 2023 were:

```{r, include=TRUE, echo=FALSE}
kable(filter(sci23, Local == 1)[, c("First", "Last", "Type", "Affiliation")], align = "ll")
```

# 2022

The members of the local organizing committee in 2022 were:

```{r, include=TRUE, echo=FALSE}
kable(select(filter(sci22, Local == 1), -Local, -SciCom, -email, -Gender), align = "llccl")
```

# Questions?

For feedback and questions send an email to `r res["chairmail"]`.



