---
title: "Instructions for presenters in the short topic session"
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

## read in data 
path <- getwd() 
source(paste(path, "/functions/inputData.r", sep = ""))
res <- inputData() 
source(paste(path, "/functions/colFmt.r", sep = ""))
``` 

# What aspects have made submissions to the short topic session successful in the past?

- Ask one or more clear questions to panel of regulators.
- Ask questions that allow for a discussion, which do not invite a yes/no answer or an obvious answer from a regulator.
- Do your homework!
  - Have similar questions been dealt with in other related areas, e.g. another therapeutic area or another quantitative field?
  - Have regulators commented on this in other instances?
  - etc.
- Reference to actual regulatory interactions, e.g. with regional differences.
- Do not ask for recipes along the lines: _If we as sponsor do X will regulators then for sure agree to it?_ 
- Before submission of a topic ask yourself: What can a regulator meaningfully answer to my questions? 

# Format of the short topic session

To guarantee the success of the session we would like to re-iterate the format:

- We have six topics distributed over two hours, which leaves each topic with 20min total time.
- You can present for five minutes using maximum two slides.
- `r colFmt("Presentation must be in person. There will be no virtual presentations in this session.")`
- Please make sure your presentation of the issue is generic enough so that everyone in the room can follow.
- Please ask one or more very explicit questions to the panel of regulators.
- Do not ask regulators for “recipes” in the sense of “if we do that then you guarantee to do that”.
- When formulating your questions ask yourself: “What would I answer if I were a regulator?” This may help to be precise and specific.

# Deadline

Please send us your slides until `r colFmt(res["deadline_short"])`.

# Questions?

For feedback and questions send an email to `r res["infomail"]`.



