---
title: "Updates on this page"
date: last-modified
execute:   
  freeze: auto  # re-render only when source changes
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

* 2024/09/30: All slidedecks for which permission for posting has been given are now available [online](https://efspieurope.github.io/workshop/data/2024/slides.html). Recordings will follow.
* 2024/06/28: Updated [draft program](https://efspieurope.github.io/workshop/data/2024/9th%20EFSPI%20RegStat%20Workshop%20program.pdf), further speakers now confirmed.
* 2024/06/10: Updated [draft program](https://efspieurope.github.io/workshop/data/2024/9th%20EFSPI%20RegStat%20Workshop%20program.pdf), further speakers now confirmed.
* 2024/06/05: Updated [draft program](https://efspieurope.github.io/workshop/data/2024/9th%20EFSPI%20RegStat%20Workshop%20program.pdf), further speakers now confirmed.
* 2024/05/31: Updated [draft program](https://efspieurope.github.io/workshop/data/2024/9th%20EFSPI%20RegStat%20Workshop%20program.pdf), many speakers now confirmed.
* 2024/05/03: Updated [draft program](https://efspieurope.github.io/workshop/data/2024/9th%20EFSPI%20RegStat%20Workshop%20program.pdf).
* 2024/04/30: Roche and Novartis again have a comprehensive block booking agreement with the workshop, see [registration FAQ](registration_faq.html#which-companies-have-block-bookings-for-face-to-face-participation).
* 2024/04/17: First version of [draft program](https://efspieurope.github.io/workshop/data/2024/9th%20EFSPI%20RegStat%20Workshop%20program.pdf) for 2024 workshop online.
* 2024/01/29: We welcome two new members to the Scientific Committee: Welcome Bergrun Tina	Magnusdottir from Iceland and Heidi	Mestl from Norway!
* 2024/01/10: The Scientific Committee for this year's workshop is complete! Find the roster [here](scicom.html).





