---
title: "Why should I attend the EFSPI regulatory statistics workshop?"
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- getwd()
source(paste(path, "/functions/colFmt.r", sep = ""))
source(paste(path, "/functions/inputData.r", sep = ""))
res <- inputData()
```

# Why should I attend the EFSPI regulatory statistics workshop at all?

- Each year, a [scientific committee](scicom.html) of statistical key opinion leaders from regulatory agencies and industry alike spend lots of time and energy to craft a program that allows exposition and discussion of key drug development topics of mutual interest. 
- Different from most other scientific conferences, all presentations and discussions are by invitation only, what allows to offer tailored and coherent sessions.
- The focus of the workshop is less on presentation of scientific results and statistical methods. Rather, the format and style is such that it fosters discussions among presenters and attendees in an open, engaging, and informal way. This, during the sessions and also during the breaks and the social event.
- Each year, several hundred drug developers from Europe, and often beyond, attend the workshop. The venue, together with extended breaks between sessions offer ample opportunity to interact, discuss, and drink coffee together with industry peers and regulatory colleagues (who are very accessible during the workshop).
- A short topic session where industry asks questions of general interest for drug developers and regulators provide their feedback and input on the spot.
- Compared to similar events the workshop is a bargain: the registration for two day face-to-face participation amounts to `r res["fee_f"]` Euro for face-to-face and `r res["fee_v"]` Euro for virtual attendance.
- For drug developers (statisticians, clinicians, industry regulatory colleagues, ...) we are not aware of an equally targeted training opportunity in Europe that fosters so much collaboration and interaction.

# What do I get for my registration fee?

On top of the above the registration fee pays for:

## Face-to-face or virtual attendance

- Travel and accommodation for invited speakers for academic institutions and regulatory agencies (industry is self-paying, even if invited).
- Live broadcast of all sessions.
- Access to slidedecks and recordings after the entire event.

## Face-to-face attendance only

- The very nice venue: [Biozentrum](https://www.biozentrum.unibas.ch/) in beautiful [Basel](https://www.basel.com/en).
- Coffee, tea, snacks, meals for two days.

# What do I not pay for with my registration fee?

- [EFSPI](https://efspi.org/) is non-profit making and as a principle does not pay any honorarium.
- An agency that organizes the conference. The entire conference is organized by unpaid volunteers from the pharmaceutical industry who do all the work on top of their day job.
- An expensive registration portal using credit card. Instead, we rely on simple free tools and bank transfer.



# Questions?

For feedback and questions send an email to `r res["chairmail"]`.



